version: '2'

services:
  jenkins:
    container_name: jenkins
    image: 'jenkins/jenkins:lts'
    restart: always
    volumes:
      - "${DOCKER_DATA_DIR}/jenkins:/var/jenkins_home"
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker:/bin/docker'
    group_add:
      - root

networks:
  default:
    external:
      name: "${DOCKER_PRIVATE_NETWORK_NAME}"