version: '3'

services:
  jenkins:
    container_name: "${DOCKER_JENKINS_CONTAINER_NAME}"
    image: 'jenkins/jenkins:lts'
    restart: always
    volumes:
      - "${DOCKER_JENKINS_DATA_DIR}:/var/jenkins_home"
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/bin/docker'
      - '/usr/lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7'
    ports:
      - 8080:8080
    environment:
      - DOCKER_NGINX_CONTAINER_NAME=${DOCKER_NGINX_CONTAINER_NAME}
      - DOCKER_NGINX_DIR=${DOCKER_NGINX_DIR}
      - DOCKER_NGINX_VHOST_DIR=${DOCKER_NGINX_VHOST_DIR}
      - DOCKER_NGINX_CA_DIR=${DOCKER_NGINX_CA_DIR}
      - DOCKER_JENKINS_CONTAINER_NAME=${DOCKER_JENKINS_CONTAINER_NAME}
      - DOCKER_JENKINS_DIR=${DOCKER_JENKINS_DIR}
      - DOCKER_JENKINS_DATA_DIR=${DOCKER_JENKINS_DATA_DIR}
      - WWWROOT_DIR=${WWWROOT_DIR}
      - LOCAL_DIR=${LOCAL_DIR}


networks:
  default:
    external:
      name: "${DOCKER_PRIVATE_NETWORK_NAME}"
