version: '2'

services:
  jenkins:
    container_name: "${DOCKER_JENKINS_CONTAINER_NAME}"
    image: 'jenkins/jenkins:lts'
    restart: always
    volumes:
      - "${DOCKER_JENKINS_DATA_DIR}:/var/jenkins_home"
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker:/bin/docker'
    group_add:
      - root
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: "${DOCKER_PRIVATE_NETWORK_NAME}"